In [1]:
import numpy as np

In [2]:
arr_0 = np.zeros(10)

In [3]:
arr_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr_1 = np.ones(10)

In [5]:
arr_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr_5 = arr_1 * 5

In [7]:
arr_5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
arr10_50 = np.arange(10,51)

In [9]:
arr10_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
arr_even = np.arange(10,51,2)

In [11]:
arr_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
a2 = np.arange(0,9)

In [13]:
a2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
a_i = np.eye(3)

In [17]:
a_i.reshape(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.rand(1)

array([0.78380097])

In [29]:
np.random.randn(25)

array([ 0.40078872,  0.93942168, -0.37224151, -0.90664916,  0.99475717,
       -0.37908413, -1.14126802,  0.27086058, -1.09119441, -0.82329336,
        1.15962289, -0.7426459 , -1.06744195, -0.27877396,  1.35110194,
       -2.50964537, -0.03033083,  0.8365733 ,  1.05090176,  0.91321823,
       -0.65876579, -0.26330676, -0.12976802,  1.55957704, -1.1761688 ])

In [32]:
np.arange(1,51)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ])

In [38]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [39]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [42]:
ar22 = np.arange(1,26)

In [54]:
ar23 = ar22.reshape(5,5)
ar23

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ar2[]

In [52]:
ar23[3][4]

20

In [76]:
ar23[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
ar23[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [59]:
np.arange(2,13,5)

array([ 2,  7, 12])

In [60]:
ar23[4]

array([21, 22, 23, 24, 25])

In [64]:
ar23[([3],[4])]

array([20])

In [66]:
np.sum(ar22)

325

In [67]:
np.std(ar22)

7.211102550927978

In [72]:
np.sum(ar23[0,:])

15

In [73]:
ar23.sum(0) #Columns or ar23.sum(axis=0)

array([55, 60, 65, 70, 75])

In [74]:
ar23.sum(1)#Rows or ar23.sum(axis=1)

array([ 15,  40,  65,  90, 115])