In [1]:
import numpy as np

In [2]:
#1
print("Version: ", np.__version__)
#np.version.version
#print("Configuration",np.show_config())

Version:  1.15.1


In [3]:
#2
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [44]:
#3
arr1 = np.array([2,3,4,5,6])  
if 0 or "0" in arr1:
    print("Array contains zero element")
else:
    print("Array contains non-zero elements")
    
#arr2 = np.array([1,2,3,4])
#print(np.all(arr2))

Array contains non-zero elements


C:\Users\AMA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  This is separate from the ipykernel package so we can avoid doing imports until


In [45]:
#4
arr22 = np.array([0,1,2,3,4,5,6])
print(np.all(arr22))

False


In [46]:
#5...Finiteness
check = 0
arr2= [1,0,np.nan,np.inf,np.NINF,np.NaN]
for i in range(len(arr2)):
    if np.isfinite(arr2[i]):
        print("Array element {} is fit. ".format(arr2[i]),np.isfinite(arr2[i]))
    else:
        print("Array element {} is not fit. ".format(arr2[i]),np.isfinite(arr2[i]))

Array element 1 is fit.  True
Array element 0 is fit.  True
Array element nan is not fit.  False
Array element inf is not fit.  False
Array element -inf is not fit.  False
Array element nan is not fit.  False


In [47]:
#6
arr3 = np.arange(-10,10)
for i in range(len(arr3)):
    if arr3[i] > 0:
        print("{} is Positive".format(arr3[i]))
    elif arr3[i] < 0:
        print("{} is Negative".format(arr3[i]))
    else:
        print("{} is Zero".format(arr3[i]))

-10 is Negative
-9 is Negative
-8 is Negative
-7 is Negative
-6 is Negative
-5 is Negative
-4 is Negative
-3 is Negative
-2 is Negative
-1 is Negative
0 is Zero
1 is Positive
2 is Positive
3 is Positive
4 is Positive
5 is Positive
6 is Positive
7 is Positive
8 is Positive
9 is Positive


In [48]:
#7
nan = [1,0,np.nan,np.inf,np.NINF,np.NaN]
for i in range(len(nan)):
    if np.isnan(nan[i]):
        print(nan[i]," is NaN")
    else:
        print(nan[i]," is not NaN")

1  is not NaN
0  is not NaN
nan  is NaN
inf  is not NaN
-inf  is not NaN
nan  is NaN


In [49]:
#8
com = [1,0,2 +2j,np.nan,np.inf,np.NINF,np.NaN,3+4j]
for i in range(len(com)):
    if np.iscomplexobj(com[i]):
        print(com[i]," is complex")
    else:
        print(com[i]," is not complex")
        

1  is not complex
0  is not complex
(2+2j)  is complex
nan  is not complex
inf  is not complex
-inf  is not complex
nan  is not complex
(3+4j)  is complex


In [50]:
#9...within tolerance
a1 = np.array([1,3,3])#np.arange(10)
a2 = np.array([1,2,3])#np.arange(9)
#print(a1 == a2)
np.equal(a1,a2).any()

True

In [51]:
#10
if np.greater(a1,a2).any():
    print("Greater")
elif np.greater_equal(a1,a2).any():
    print(">=")
elif np.less(a1,a2):
    print("<")
elif np.less_equal(a1,a2).any():
    print("<=")
else:
    print("IDk")

Greater


In [12]:
#11


In [13]:
#12

In [52]:
#13
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)
#print(np.zeros(10)+5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [53]:
#14 int from 30 to 70
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [54]:
#15 even int from 30 to 70
np.arange(30,71,2)


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [55]:
#19
np.arange(16,55)

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [56]:
#20
ar = np.ones(12)
ar = ar.reshape(3,4)
for i in range(ar.shape[0]):
    for j in range(ar.shape[1]):
        print(ar[i][j])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [57]:
#21
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [58]:
#22
ve = np.arange(21)
vec = ve.reshape(3,7)
for i in range(vec.shape[0]):
    for j in range(vec.shape[1]):
        if vec[i][j] >= 9 and vec[i][j] <= 15:
               vec[i][j] = -(vec[i][j])
vec

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,  -9, -10, -11, -12, -13],
       [-14, -15,  16,  17,  18,  19,  20]])

In [59]:
#23
from random import randint
vecc = np.random.randint(0,10,5)
vecc

array([2, 3, 1, 6, 1])

In [60]:
#24
vec1 = np.random.randint(0,10,5)
vec2 = np.random.randint(0,10,5)
res = vec1 * vec2
print("Result of {} * {} = ".format(vec1,vec2),res)

Result of [9 4 4 8 7] * [8 1 6 1 5] =  [72  4 24  8 35]


In [61]:
#25
vector = np.random.randint(10,22,12)
vector = vector.reshape(3,4)
vector

array([[15, 14, 13, 13],
       [21, 18, 21, 14],
       [18, 17, 17, 16]])

In [62]:
#26
print("Number of rows and columns in array(vector): ")
vector.shape
print("Rows:",vector.shape[0])
print("Columns:",vector.shape[1])

Number of rows and columns in array(vector): 
Rows: 3
Columns: 4


In [63]:
#27
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
#28
ones_zeros = np.zeros(100)
ones_zeros = ones_zeros.reshape(10,10)

for i in range(0,10,9):
    for j in range(10):
        ones_zeros[i][j] = 1
        ones_zeros[j][i] = 1
    
ones_zeros

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
#29
five_zeros = np.eye(5)
for i in range(5):
    for j in range(5):
        if i == j:
            five_zeros[i][j] = j+1
    
five_zeros

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [66]:
#30
four_stag = np.random.randint(0,2,16)
four_stag = four_stag.reshape(4,4)
for i in range(4):
    for j in range(4):
        if i == j:
            four_stag[i][j] = 0
    
four_stag

array([[0, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
#31
tb = np.random.randint(0,100,27)
tb = tb.reshape(3,3,3)
tb

array([[[74,  8, 81],
        [49, 52, 18],
        [48, 19, 16]],

       [[46, 80, 35],
        [87, 45, 92],
        [55,  9, 43]],

       [[35, 48, 44],
        [32, 80, 58],
        [45, 96, 16]]])

In [68]:
#32
sum_arr = np.random.randint(0,100,25)
sum_arr = sum_arr.reshape(5,5)
print("Total sum: ",sum_arr.sum())
print("Sum of Rows: ",sum_arr.sum(axis=0))
print("Sum of Columns: ",sum_arr.sum(axis=1))

Total sum:  1414
Sum of Rows:  [263 289 251 294 317]
Sum of Columns:  [293 164 311 316 330]


In [69]:
#33
mul_ar1 = np.random.randint(0,20,9).reshape(3,3)
mul_ar2 = np.random.randint(0,20,9).reshape(3,3)
mul_res = mul_ar1 * mul_ar2
print(mul_res)

np.dot(mul_ar1,mul_ar2)

[[144   8 144]
 [114 119   2]
 [ 76 108  48]]


array([[230, 134, 244],
       [399, 149, 114],
       [594, 238, 312]])

In [70]:
#34

row = np.arange(8)
row = row.reshape(4,2)
print("initial: \n", row)
for i in range(4):
    row[i:] += [2,3]
row

initial: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


array([[ 2,  4],
       [ 6,  9],
       [10, 14],
       [14, 19]])

In [71]:
#35
bin_array = np.random.randint(1,9,10)
bin_file = open("bin_file.txt","wb")

bin_file.write(bin_array)
bin_file.close()

binn = open("bin_file.txt","r")
print(binn.read())
#print(binn.readlines())
binn.close()

import os

np.save("binfile.npy",bin_array)
if os.path.exists("binfile.npy"):
    bina = np.load("binfile.npy")
    print(np.array_equal(bin_array,bina))


True


In [72]:
#36
zipped1 = np.random.randint(1,9,10)
zipped2 = np.random.randint(1,20,12)

zipped = open("zipped.npz","wb")

zipped.write(zipped1)
zipped.write(zipped2)
zipped.close()

zipp = open("zipped.npz","r")
p = zipp.read()
print(p)
zipp.close()






In [73]:
#37
str_arr = np.random.randint(1,9,10)

dd = ""
for i in range(len(str_arr)):
    dd += str(str_arr[i])

list_str = open("list.txt","w")
list_str.write(dd)
list_str.close()

prin = open("list.txt","r")
c = prin.read()
ddd = []
for i in range(len(c)):
    ddd.append(int(c[i]))
    
print(ddd)
#print(list(c))
prin.close()

[5, 6, 6, 5, 6, 6, 5, 3, 6, 3]


In [36]:
#38

In [37]:
#39 
gg = [1,2,3,4]
list(list(gg))

[1, 2, 3, 4]

In [38]:
import matplotlib as plt